### ISSUE TITLE
sourcemap not working

### ISSUE THREAD

**Issue by forresto** [forresto/system-coffee#1]
Not sure if this is a Chrome, jspm, or systemjs issue:

The sourcemap isn't quite working... in Chrome clicking on `test.coffee:10` shows the output js, not the [CoffeeScript](https://github.com/forresto/plugin-coffee/blob/master/test.coffee) (file name right, line number is right for generated js):

![screen shot 2015-01-13 at 3 32 10 pm](https://cloud.githubusercontent.com/assets/395307/5728596/7442afd4-9b39-11e4-866a-ec95a80d0e3d.png)

---

Firefox is more broken, with that console.log coming back as `test.html:9` (file name and line number wrong).

**Comment by forresto** [comment]
Ideas @guybedford?

**Comment by guybedford** [comment]
@forresto this is a new feature that will only work when Traceur 0.0.82 lands.

**Comment by forresto** [comment]
OK, nice.

**Comment by jussiry** [comment]
I can't get source maps to work on neither Traceur (0.0.88) nor Babel (5.1.13).

**Comment by guybedford** [comment]
Thanks, yes this was a regression in SystemJS. I've added https://github.com/systemjs/systemjs/issues/497.

**Comment by guybedford** [comment]
The next SystemJS will have a patch to fix this. This will work with the PR - https://github.com/forresto/system-coffee/pull/7.
