### ISSUE TITLE
Use CoffeeScript as a dependency

### ISSUE THREAD

**Issue by guybedford** [forresto/system-coffee#2]
Am I right in thinking the reason this isn't being done at the moment is because of the `require('module')` issue?

It would be nice to get this working properly, will see if I can fix the issue.

**Comment by victorwpbastos** [comment]
Would be great!

**Comment by forresto** [comment]
Yes, I was using `window.CoffeeScript`, but then saw `require('./coffee-script')` at least works.

**Comment by victorwpbastos** [comment]
Works in bundle also?

Atenciosamente,

Victor Bastos
Em 14/01/2015 13:48, "Forrest Oliphant" <notifications@github.com> escreveu:

**Comment by forresto** [comment]
Would be better as a proper dependency!

**Comment by victorwpbastos** [comment]
Do you can make bundles too?

**Comment by forresto** [comment]
Maybe not til https://github.com/jspm/npm/issues/39

**Comment by forresto** [comment]
Gave it another shot: https://github.com/forresto/plugin-coffee/commit/7e223bdaccaa8ba979a78785d71e1c762069bacd

Looks like it is loading everything, but in the console I'm getting:

> Uncaught Node child_process module not supported in browsers.
> system.src.js:2239 Uncaught Error evaluating http://localhost:3000/jspm_packages/github/jspm/nodelibs-child_process@0.1.0/index.js
> Uncaught Node child_process module not supported in browsers.
> system.src.js:2239 Uncaught Error evaluating http://localhost:3000/jspm_packages/github/jspm/nodelibs-child_process@0.1.0.js
> Uncaught Error evaluating http://localhost:3000/jspm_packages/github/jspm/nodelibs-child_process@0.1.0/index.js
> Uncaught Node child_process module not supported in browsers.
> test.html:15 ERROR:  Error loading "test.coffee!coffee" at <unknown>

Seems like including the browser build is still needed.
